### PR TITLE
Add initial version of the demo

### PR DESCRIPTION
**Pull request by northern-64bit**

### CODE REVIEW

**Review by zachschillaci27 — APPROVED** [review]
LGTM

**Comment by zachschillaci27** [comment]
Note we will need to add proper attribution for our partners at HES-SO, but let's add them to the repo first :)

**Comment by zachschillaci27** [comment]
Oops please add a `requirements.txt` file when you can

**Comment by northern-64bit** [comment]
> Note we will need to add proper attribution for our partners at HES-SO, but let's add them to the repo first :)

Sounds good!

**Pull request merged**
